### PR TITLE
Fix for jQuery 3.0 load() deprecation. Fixes #778

### LINKED ISSUE #778: cycle2 & center incompatible with JQuery 3.0.0
The indexOf operator that is employed in cycle2 and center's code is causing conflicts with JQuery 3.0.0...apparently this has to do with $(window).load(function() { ... }); vs $(window).on('load', function() { ... }); elsewhere in the code, and parameters passed to:

 r.fn.load = function(a, b, c) {
        var d, e, f, g = this, h = a.indexOf(" ");

...in the minified version are throwing a "a.indexOf is not a function" type error, presumably where "a" is related to the loading. See this StackOverflow article for more info:

https://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error

### PR DESCRIPTION
**Pull request by jakeparis**
jQuery 3.0 has deprecated the load function. In this case, we wanted to check for something on the load _event_ anyway, so we switch to using .on('load')

### CODE REVIEW

**Comment by dmethvin** [comment]
LGTM ... in the meantime you should be able to use jQuery Migrate 3.0 to get the current version running again.

**Comment by robinwilson16** [comment]
Thanks for your fix. I can confirm this resolves the issue with the latest version of jQuery.
I notice that no changes seem to have been committed for over two years so am wondering if this project is still active?

**Comment by ghost** [comment]
I think the project is dead.

**Comment by jakeparis** [comment]
Yes, but it still works well.

**Comment by ghost** [comment]
@jakeparis yeap, we use it too. But, I think the author should give other persons write access to maintain the project if he can't.

**Comment by robinwilson16** [comment]
It's a shame as Cycle2 is a really nice plugin

**Comment by ghost** [comment]
@malsup are you alive?

**Comment by tmuka** [comment]
thanks for this fix.  after it cycle2 worked with my jquery v3.2.1.

**Comment by FisherFast** [comment]
Thank you so much for the fix. That fixed one of my slide shows, but I also use the [carousel feature](http://jquery.malsup.com/cycle2/demo/carousel.php) with Cycle2 and that has an additional [jquery file](http://malsup.github.io/jquery.cycle2.carousel.js). This feature doesn't seem to work with jquery 3.0.

**Is there any way to tell what might need to be updated to get the carousel to work with Jquery 3.0?**

**Comment by BackuPs** [comment]
You can download a jquery 4.0 compatible version here https://github.com/BackuPs/cycle2/tree/master
